pyuic5 windows/EmployeeWindow.ui -o scripts/employeeWindow_ui.py
pyuic5 windows/LoginWindow.ui -o scripts/loginWindow_ui.py
pyuic5 windows/DayRequestWindow.ui -o scripts/dayRequestWindow_ui.py
pyuic5 windows/CancelRequestWindow.ui -o scripts/cancelRequestWindow_ui.py
pyuic5 windows/RequestsWidget.ui -o scripts/requestsWidget_ui.py
pyuic5 windows/EmployeeWidget.ui -o scripts/employeeWidget_ui.py
pyuic5 windows/AdmDaysDialog.ui -o scripts/admDaysDialog_ui.py
pyuic5 windows/NotificationsWidget.ui -o scripts/notificationsWidget_ui.py
pyuic5 windows/FeriadosDialog.ui -o scripts/feriadosDialog_ui.py
pyuic5 windows/ModificarFeriadosDialog.ui -o scripts/modificarFeriadosDialog_ui.py
pyuic5 windows/RestriccionesDialog.ui -o scripts/restriccionesDialog_ui.py
pyrcc5 images/Resource_ha.qrc -o scripts/Resource_ha_rc.py
