dist: xenial
language: python

services:
  # to be able to display
  - xvfb

before_install:
  - sudo apt-get update

matrix:
  include:
    - python: 3.6
      env: TOXENV=py36
    - python: 3.6
      env: TOXENV=py36-pyqt5
    - python: 3.6
      env: TOXENV=py36-pyside2

install:
  # to make sure it has everything up to date
  - pip install -U setuptools
  - pip install -U pip
  - pip install -U wheel
  - pip install -U virtualenv
  - pip install -U tox

script:
  - tox
